import JSZip from 'jszip';

export async function downloadProject(html: string, css: string, js: string) {
  const zip = new JSZip();
  zip.file('index.html', html);
  
  const tailwindCss = `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n${css}`;
  zip.file('styles.css', tailwindCss);
  
  zip.file('script.js', js);
  
  zip.file('package.json', JSON.stringify({
    name: 'webforge-project',
    version: '1.0.0',
    description: 'Project generated by WebForgeAI',
    scripts: {
      "dev": "npx tailwindcss -i ./styles.css -o ./output.css --watch"
    },
    devDependencies: {
      "tailwindcss": "^3.4.1"
    }
  }, null, 2));

  zip.file('tailwind.config.js', `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./script.js"],
  theme: {
    extend: {},
  },
  plugins: [],
}`);

  const content = await zip.generateAsync({ type: 'blob' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(content);
  link.download = 'webforge-project.zip';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}
